// Generated from the Rust IPC surface by `cargo run --bin export-bindings --features export-bindings`.
// Do NOT edit by hand: the next export overwrites it, and CI fails when the
// committed file differs from a fresh export.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startKernel: () => typedError<KernelState, AppError>(__TAURI_INVOKE("start_kernel")),
	stopKernel: () => typedError<KernelState, AppError>(__TAURI_INVOKE("stop_kernel")),
	restartKernel: () => typedError<KernelState, AppError>(__TAURI_INVOKE("restart_kernel")),
	getKernelState: () => __TAURI_INVOKE<KernelState>("get_kernel_state"),
	getMihomoVersion: () => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_version")),
	getMihomoConfigs: () => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_configs")),
	/**  PATCH /configs — outbound mode switch (`{"mode": "rule"}`), etc. */
	patchMihomoConfig: (mode: string) => typedError<null, AppError>(__TAURI_INVOKE("patch_mihomo_config", { mode })),
	/**
	 *  PUT /configs — hot-reload. `path: None` reloads the current config;
	 *  `Some(path)` loads that yaml file. `force` mirrors `?force=true`.
	 */
	reloadMihomoConfig: (path: string | null, force: boolean | null) => typedError<null, AppError>(__TAURI_INVOKE("reload_mihomo_config", { path, force })),
	getMihomoProxies: () => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_proxies")),
	/**  GET /proxies/{name} — single proxy / group read. */
	getMihomoProxy: (name: string) => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_proxy", { name })),
	/**
	 *  PUT /proxies/{group} — switch the active child of a Selector group.
	 *  Mihomo answers the PUT with 204 (empty body) on success, so we then
	 *  re-GET the group and return its authoritative JSON — the renderer never
	 *  sees a bare `null` payload it would crash on. A failed re-GET is NOT
	 *  fatal: the switch already happened, so we degrade to `null` and the
	 *  frontend falls back to optimistic state.
	 */
	selectMihomoProxy: (group: string, proxy: string) => typedError<string, AppError>(__TAURI_INVOKE("select_mihomo_proxy", { group, proxy })),
	/**  GET /proxies/{name}/delay?url=…&timeout=… */
	getMihomoProxyDelay: (name: string, url: string | null, timeoutMs: number | null) => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_proxy_delay", { name, url, timeoutMs })),
	getMihomoConnections: () => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_connections")),
	closeMihomoConnection: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("close_mihomo_connection", { id })),
	closeAllMihomoConnections: () => typedError<null, AppError>(__TAURI_INVOKE("close_all_mihomo_connections")),
	getMihomoRules: () => typedError<string, AppError>(__TAURI_INVOKE("get_mihomo_rules")),
	/**
	 *  Probe every node in `nodes` concurrently and stream the results.
	 * 
	 *  * `group`       — the owning group; used for cancellation and so the UI can
	 *                    route a batch to the right card set.
	 *  * `nodes`       — node names to probe. The caller filters out the
	 *                    un-probeable types (`Direct`, `Reject`, …) because only it
	 *                    knows the proxy tree.
	 *  * `url`         — probe target; defaults to the 204 endpoint.
	 *  * `timeout_ms`  — Mihomo's per-probe budget; defaults to 5000.
	 *  * `concurrency` — in-flight cap; defaults to 64, clamped by the engine.
	 * 
	 *  Returns the run id. Every result carries it, so a client that superseded a
	 *  run can drop the stragglers — and so can we.
	 */
	speedTestGroup: (group: string, nodes: string[], url: string | null, timeoutMs: number | null, concurrency: number | null) => typedError<number, AppError>(__TAURI_INVOKE("speed_test_group", { group, nodes, url, timeoutMs, concurrency })),
	/**
	 *  Cancel the run currently owning `group`.
	 * 
	 *  Idempotent: cancelling an idle group is a successful no-op. The run stops at
	 *  its next probe completion and still emits a terminal
	 *  `proxy://delay-done` with `cancelled: true`, so the UI always gets to clear
	 *  its spinners.
	 */
	cancelSpeedTest: (group: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_speed_test", { group })),
	/**
	 *  Check GitHub's update feed for a newer release. Returns `None` when the
	 *  current version is already the latest. Network failures are surfaced as
	 *  readable errors — never panics, never crashes the renderer.
	 */
	checkUpdate: () => typedError<{
	/**  Version announced by the remote feed (e.g. "0.2.1"). */
	version: string,
	/**  Version currently installed in this build. */
	currentVersion: string,
	/**  Release body / notes, if the feed carries them. */
	body: string | null,
} | null, string>(__TAURI_INVOKE("check_update")),
	/**
	 *  Download the latest update and trigger install. Progress is emitted as
	 *  `updater://progress` with `{ downloaded, total }`; `total` may be null
	 *  until the server reports a content length.
	 */
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
	listProfiles: () => typedError<ProfileMeta[], AppError>(__TAURI_INVOKE("list_profiles")),
	getActiveProfile: () => typedError<{
	/**
	 *  Stable id (UUID v4 string) used in directory names and as the
	 *  identifier in Tauri commands.
	 */
	id: string,
	/**  Human-friendly name shown in the UI. */
	name: string,
	/**  Source URL (for subscriptions). Empty for pasted/imported-from-file. */
	url?: string,
	/**  Node count (populated when the yaml is sanitised; `0` if unknown). */
	node_count?: number,
	/**  Last-write time (UTC, ISO-8601). */
	updated_at: string,
	/**  Absolute path to the on-disk yaml. */
	file_path: string,
	/**  Bytes used (download), if the subscription header reported it. */
	used_bytes?: number | null,
	/**  Bytes remaining (total - used), if available. */
	remaining_bytes?: number | null,
	/**  Total quota, if available. */
	total_bytes?: number | null,
	/**  Expire timestamp (UTC), if the header reported one. */
	expire_at?: string | null,
} | null, AppError>(__TAURI_INVOKE("get_active_profile")),
	getProfileContent: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("get_profile_content", { id })),
	saveProfile: (id: string | null, name: string, content: string) => typedError<ProfileMeta, AppError>(__TAURI_INVOKE("save_profile", { id, name, content })),
	deleteProfile: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_profile", { id })),
	importProfileUrl: (url: string, name: string) => typedError<ProfileMeta, AppError>(__TAURI_INVOKE("import_profile_url", { url, name })),
	importProfileFile: (path: string, name: string) => typedError<ProfileMeta, AppError>(__TAURI_INVOKE("import_profile_file", { path, name })),
	/**
	 *  Re-fetch an existing subscription profile (M6).
	 * 
	 *  Fetches the original `url` (must be non-empty), sanitises the yaml,
	 *  preserves the profile `id` so a subsequent `set_active_profile` is
	 *  unaffected, and refreshes the `subscription-userinfo` quota fields.
	 *  If the updated profile is the active one we additionally hot-reload
	 *  mihomo so the new node list takes effect immediately.
	 */
	updateSubscription: (id: string) => typedError<ReloadResult, AppError>(__TAURI_INVOKE("update_subscription", { id })),
	setActiveProfile: (id: string) => typedError<ReloadResult, AppError>(__TAURI_INVOKE("set_active_profile", { id })),
	/**
	 *  `rename_profile` — Patch a profile's display `name` in the index file.
	 *  Used by the UI's card-level "rename" action. Empty / whitespace-only
	 *  names are rejected with `AppError::Config`.  The yaml file is left
	 *  alone (its file name remains the id-derived directory), but the
	 *  `ProfileIndex` is rewritten so the list reflects the new label.
	 */
	renameProfile: (id: string, name: string) => typedError<ProfileMeta, AppError>(__TAURI_INVOKE("rename_profile", { id, name })),
	/**
	 *  `open_profile_in_editor` — Hand the on-disk yaml to whatever the
	 *  user has registered for `.yaml` (Notepad, VS Code, etc.).  We use
	 *  `ShellExecuteW` with the `edit` verb when the association supports
	 *  it, falling back to the `open` verb.  No-op stub on non-Windows.
	 */
	openProfileInEditor: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_profile_in_editor", { id })),
	/**
	 *  `reveal_profile_file` — Open the profile's containing folder in
	 *  Explorer with the file already selected. Implemented via the
	 *  Win32 `SHOpenFolderAndSelectItems` shell API, which is exactly
	 *  what `explorer.exe /select,"path"` does under the hood.  Stub on
	 *  non-Windows: prints the parent dir to stderr.
	 */
	revealProfileFile: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_profile_file", { id })),
	/**
	 *  Turn the Windows system proxy on, pointing at `127.0.0.1:<port>`.
	 *  If `port` is None we use mihomo's default mixed-port (7897).
	 */
	enableSystemProxy: (port: number | null) => typedError<ProxyToggleResult, AppError>(__TAURI_INVOKE("enable_system_proxy", { port })),
	disableSystemProxy: () => typedError<ProxyToggleResult, AppError>(__TAURI_INVOKE("disable_system_proxy")),
	getSystemProxyStatus: () => typedError<{
	/**  Whether the user has the system proxy enabled (ProxyEnable=1). */
	enabled: boolean,
	/**
	 *  Raw "host:port" string. May be empty even when `enabled` is true
	 *  (rare but possible on freshly-built Windows images).
	 */
	server: string,
	/**  Current `ProxyOverride` (bypass rules) — informational only. */
	override_rules: string,
} | null, AppError>(__TAURI_INVOKE("get_system_proxy_status")),
	/**
	 *  Read the actual `HKCU\...\Run\FlexClash` state via the autostart plugin.
	 *  Plugins store this under the app identifier on Windows.
	 */
	getAutostartStatus: () => __TAURI_INVOKE<AutostartStatus>("get_autostart_status"),
	/**
	 *  Enable or disable the autostart entry. When enabling on Windows, the
	 *  plugin writes `HKCU\Software\Microsoft\Windows\CurrentVersion\Run\FlexClash`
	 *  pointing at our binary with the `--silent` argument, so the next boot
	 *  starts in the tray.
	 * 
	 *  Enabling this also removes the elevated logon task, for the reason
	 *  spelled out above.
	 */
	setAutostart: (enabled: boolean) => typedError<AutostartStatus, AppError>(__TAURI_INVOKE("set_autostart", { enabled })),
	getSilentAutostartStatus: () => __TAURI_INVOKE<SilentAutostartStatus>("get_silent_autostart_status"),
	/**
	 *  Enable the elevated logon task. **Shows a UAC prompt.**
	 * 
	 *  Ordering is deliberate: the registry entry is removed *first*. If the
	 *  task creation is then cancelled at the UAC prompt we are left with no
	 *  autostart at all — which is recoverable by flicking the switch again —
	 *  whereas the reverse order could leave both mechanisms armed and produce
	 *  the double-launch the exclusion exists to prevent.
	 */
	setSilentAutostart: (enabled: boolean) => typedError<SilentAutostartStatus, AppError>(__TAURI_INVOKE("set_silent_autostart", { enabled })),
	/**  Read the silent-launch flag (set once at boot from `argv`). */
	getSilentFlag: () => __TAURI_INVOKE<boolean>("get_silent_flag"),
	/**
	 *  Run the residual-route sweep (M9 hook, no-op in M7). Exposed so the
	 *  frontend can show "checked for leftover routes" feedback even when the
	 *  real implementation is not yet wired in.
	 */
	sweepResidualRoutes: () => __TAURI_INVOKE<SweepResult>("sweep_residual_routes"),
	/**
	 *  Cheap status read. Frontend polls this on mount + on every
	 *  `tun://state-changed` event so the toggle always reflects the
	 *  authoritative backend state.
	 */
	getTunState: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("get_tun_state")),
	/**
	 *  Enable TUN. Triggers the full state machine:
	 *    * sweep → patch config → runas-elevate mihomo → wait for healthy
	 *    * on any failure, roll back to Off/Failed and surface the error.
	 * 
	 *  `strict_route` / `dns_hijack` are the two Settings -> "TUN Advanced"
	 *  switches. They are stamped onto the `tun:` block during the config patch
	 *  (step 2), which is the only moment the yaml is ours to rewrite — the
	 *  elevated kernel then boots straight from it.
	 * 
	 *  `rename_all = "snake_case"` is deliberate: Tauri 2 defaults command
	 *  arguments to camelCase, and pinning the convention here is what keeps the
	 *  Rust parameter names and the `invoke` payload in `src/services/tun.ts`
	 *  from silently drifting apart.
	 */
	enableTun: (strictRoute: boolean | null, dnsHijack: boolean | null) => typedError<TunStatus, AppError>(__TAURI_INVOKE("enable_tun", { strictRoute, dnsHijack })),
	/**
	 *  Push a changed "TUN Advanced" switch into the *running* kernel.
	 * 
	 *  Without this the two cards would only take effect on the next
	 *  disable/enable cycle, so the UI would show "on" while `config.yaml` —
	 *  and therefore mihomo — still disagreed.
	 * 
	 *  The yaml is re-stamped first and the hot-reload second, so a failed
	 *  reload (controller briefly unreachable, kernel restarting) still leaves a
	 *  correct file behind for the next start; the failure is logged rather than
	 *  surfaced, because the persisted switch is not lost. With TUN off this is
	 *  a no-op: there is no kernel holding the old yaml.
	 */
	applyTunAdvanced: (strictRoute: boolean, dnsHijack: boolean) => typedError<TunStatus, AppError>(__TAURI_INVOKE("apply_tun_advanced", { strictRoute, dnsHijack })),
	/**
	 *  Disable TUN. Symmetric to `enable_tun`; rolls forward even on
	 *  partial failure (best-effort cleanup) and returns the final state.
	 */
	disableTun: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("disable_tun")),
	/**
	 *  Best-effort sweep exposed for the "fix it now" button on the UI.
	 *  Returns the M9 richer shape (`SweepResultFull`) so the UI can
	 *  render routes + adapters separately.
	 */
	sweepTunRoutes: () => typedError<SweepResultFull, AppError>(__TAURI_INVOKE("sweep_tun_routes")),
	/**
	 *  Fetch a pre-aggregated traffic history for one of the three ranges.
	 *  The buckets are zero-filled so the frontend can render a continuous
	 *  line even when the kernel was off for part of the window.
	 */
	getTrafficHistory: (range: string) => typedError<TrafficHistory, AppError>(__TAURI_INVOKE("get_traffic_history", { range })),
	/**
	 *  Diagnostic: absolute path of the SQLite file. Used by the
	 *  "where is my data stored?" line in the settings card.
	 */
	getHistoryDbPath: () => __TAURI_INVOKE<string>("get_history_db_path"),
	/**
	 *  Count of stored samples. Used by the live-monitor chip on the
	 *  history view to show "currently buffering N rows".
	 */
	getHistorySampleCount: () => typedError<number, AppError>(__TAURI_INVOKE("get_history_sample_count")),
	resetApplication: () => typedError<ResetReport, AppError>(__TAURI_INVOKE("reset_application")),
};

/* Types */
export type AppError = string;

/**  Lightweight snapshot broadcast to the renderer each tick. */
export type AppStateSnapshot = {
	/**  Mihomo sidecar is up (Running state — no network probe needed). */
	kernelOnline: boolean,
	/**  System proxy currently active (platform query). */
	systemProxyActive: boolean,
	/**  Instantaneous egress bytes/sec (derived from /connections totals). */
	uploadSpeed: number,
	/**  Instantaneous ingress bytes/sec. */
	downloadSpeed: number,
	/**  Outbound mode: rule / global / direct. */
	currentMode: string,
};

export type AutostartStatus = {
	enabled: boolean,
	silent: boolean,
};

/**  Incremental progress push — one event per `BATCH_SIZE` results. */
export type DelayBatch = {
	runId: number,
	group: string,
	results: NodeProbe[],
	/**  Nodes probed so far (including this batch). */
	done: number,
	total: number,
};

/**
 *  Terminal push — exactly one per run, always emitted, including on
 *  cancellation, so the UI can always clear its "testing" affordances.
 */
export type DelayDone = {
	runId: number,
	group: string,
	total: number,
	/**  How many were actually probed. `< total` iff `cancelled`. */
	done: number,
	ok: number,
	failed: number,
	cancelled: boolean,
};

/**  One row of aggregated history data. `ts` is the bucket START (epoch ms). */
export type HistoryPoint = {
	ts: number,
	upload: number,
	download: number,
};

export type KernelState = "stopped" | "starting" | "running" | "stopping" | "crashed";

/**  One node's probe result. */
export type NodeProbe = {
	name: string,
	status: ProbeStatus,
	/**  RTT in ms; `Some` iff `status == Ok`. */
	delayMs: number | null,
	/**  Human-readable detail for non-`Ok` results (shown in tooltips). */
	message: string | null,
};

/**
 *  Terminal outcome of one probe. Mirrors the frontend `DelayStatus` union
 *  (minus `idle`/`testing`, which are client-side-only states).
 */
export type ProbeStatus = 
/**  Mihomo measured an RTT. */
"ok" | 
/**  Probe budget exhausted (Mihomo 504/408, or a zero/absent delay). */
"timeout" | 
/**  The controller could not be reached at all — usually "kernel not running". */
"unreachable" | 
/**  Anything else: unknown node, malformed body, HTTP 4xx/5xx. */
"error";

/**
 *  A profile as the renderer sees it.
 * 
 *  Serves double duty: it is the shape persisted in `index.json` **and** the
 *  return type of five Tauri commands (`list_profiles`, `get_active_profile`,
 *  `save_profile`, `import_profile_url` / `import_profile_file`,
 *  `rename_profile`).
 * 
 *  The four quota/expiry fields used to carry
 *  `skip_serializing_if = "Option::is_none"`. That is gone: those attributes
 *  make serde emit a *different* shape depending on the value, which
 *  `tauri-specta` can only describe by splitting the type into
 *  `ProfileMeta_Serialize | ProfileMeta_Deserialize` — and that union is what
 *  `Option<ProfileMeta>` then inlines anonymously, leaving the renderer unable
 *  to name the result of `get_active_profile` at all. Plain `Option` writes an
 *  explicit `null` instead of dropping the key, which `#[serde(default)]`
 *  reads back as `None`, so old and new `index.json` files both round-trip.
 */
export type ProfileMeta = {
	/**
	 *  Stable id (UUID v4 string) used in directory names and as the
	 *  identifier in Tauri commands.
	 */
	id: string,
	/**  Human-friendly name shown in the UI. */
	name: string,
	/**  Source URL (for subscriptions). Empty for pasted/imported-from-file. */
	url?: string,
	/**  Node count (populated when the yaml is sanitised; `0` if unknown). */
	node_count?: number,
	/**  Last-write time (UTC, ISO-8601). */
	updated_at: string,
	/**  Absolute path to the on-disk yaml. */
	file_path: string,
	/**  Bytes used (download), if the subscription header reported it. */
	used_bytes?: number | null,
	/**  Bytes remaining (total - used), if available. */
	remaining_bytes?: number | null,
	/**  Total quota, if available. */
	total_bytes?: number | null,
	/**  Expire timestamp (UTC), if the header reported one. */
	expire_at?: string | null,
};

export type ProxyStatus = {
	/**  Whether the user has the system proxy enabled (ProxyEnable=1). */
	enabled: boolean,
	/**
	 *  Raw "host:port" string. May be empty even when `enabled` is true
	 *  (rare but possible on freshly-built Windows images).
	 */
	server: string,
	/**  Current `ProxyOverride` (bypass rules) — informational only. */
	override_rules: string,
};

export type ProxyToggleResult = {
	enabled: boolean,
	port: number | null,
	detail: string,
};

export type ReloadResult = {
	status: ReloadStatus,
	detail: string,
};

export type ReloadStatus = 
/**  mihomo was running and reload succeeded. */
"reloaded" | 
/**  mihomo is not running; the active yaml has been staged for next start. */
"staged" | 
/**  mihomo is running; reload failed AND restart fallback also failed. */
"failed";

export type ResetReport = {
	/**  Items removed (for the success modal). */
	removed_profiles: number,
	removed_history_bytes: number,
	swept_routes: boolean,
	proxy_disabled: boolean,
	kernel_was_running: boolean,
	tun_was_on: boolean,
	detail: string,
};

/**  Status of the elevated (Task Scheduler) autostart. */
export type SilentAutostartStatus = {
	/**  The logon task is registered. */
	enabled: boolean,
	/**
	 *  False on non-Windows, or where the platform cannot support it. The
	 *  UI hides/disables the switch rather than offering a control that
	 *  can only fail.
	 */
	available: boolean,
	/**
	 *  True while the registry entry is the active mechanism, so the UI can
	 *  explain which of the two mutually exclusive switches is in charge.
	 */
	registry_active: boolean,
};

/**
 *  M7-shape sweep result kept stable for the `sweep_residual_routes`
 *  Tauri command. `deleted = deleted_routes + deleted_adapters`.
 */
export type SweepResult = {
	deleted: number,
	ok: boolean,
};

/**
 *  Result of a full route/adapter sweep — the rich shape, carrying the
 *  per-kind breakdown plus a diagnostic message.
 * 
 *  Named `SweepResultFull`, not `SweepResult`, because `core::startup`
 *  already exports a `SweepResult` (the M7-era `{ deleted, ok }`
 *  projection kept for the `sweep_residual_routes` command). Two IPC
 *  types cannot share one name — specta refuses to export them both —
 *  and `Full` is the suffix the renderer has always used for this shape
 *  (`src/services/tun.ts`), so the generated name matches it.
 */
export type SweepResultFull = {
	/**  How many routing-table entries were removed. */
	deleted_routes: number,
	/**  How many virtual NICs were removed (0 on non-Windows). */
	deleted_adapters: number,
	/**  True when the sweep completed without raising any error. */
	ok: boolean,
	/**  Diagnostic message (best-effort, never an error). */
	message: string,
};

/**
 *  Result of `query_history()`. The frontend renders `buckets` directly
 *  onto the chart; `totals` are shown as headline numbers.
 */
export type TrafficHistory = {
	range: string,
	bucket_ms: number,
	buckets: HistoryPoint[],
	total_upload: number,
	total_download: number,
};

/**
 *  Public TUN state, serialised both to the frontend (event payload) and
 *  the `get_tun_state` Tauri command.
 */
export type TunState = 
/**  User has TUN off (default). */
"off" | 
/**
 *  Enable request is in flight (writing config, sweeping, requesting
 *  elevation). UI should show a spinner.
 */
"enabling" | 
/**  Elevated mihomo is up and reported TUN active. */
"on" | 
/**  Disable request is in flight (reloading config, sweeping). */
"disabling" | 
/**
 *  The most recent transition failed. The user-visible reason is
 *  stored alongside (e.g. "UAC cancelled", "elevated mihomo did
 *  not become healthy in 8s"). `last_error` is a separate field
 *  so the UI can keep showing the state badge while the toast
 *  fades.
 */
"failed";

export type TunStatus = {
	state: TunState,
	enabled: boolean,
	device: string,
	last_error: string | null,
	last_changed_at_ms: number,
	/**
	 *  Last sweep outcome (richer than the M7 contract; UI may use the
	 *  `message` field to render a small status hint).
	 */
	last_sweep: SweepResultFull | null,
};

/**  Lightweight update descriptor pushed to the UI. */
export type UpdateInfo = {
	/**  Version announced by the remote feed (e.g. "0.2.1"). */
	version: string,
	/**  Version currently installed in this build. */
	currentVersion: string,
	/**  Release body / notes, if the feed carries them. */
	body: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

